# 更新功能(这个功能展示没有用)
# 整个配置文件都没有用
updata:
  #检查更新(暂时没有用)
  check: false
  #自动更新(需开启检查更新但暂时没有用)
  auto: false
player:
  # 玩家的延迟显示(low=0~79,medium=80~119,high=120+)
  ping:
    low: "§a"
    medium: "§e"
    high: "§c"
  # 玩家设备的系统
  DeviceOS:
    Android: "安卓"
    iOS: "苹果"
    macOS: "苹果但是电脑"
    Fire_OS: "Fire_OS"
    Gear_VR: "Gear_VR"
    HoloLens: "HoloLens"
    Windows_10: "Windows 10"
    Windows: "Windows"
    Dedicated: "Dedicated"
    tvOS: "tvOS"
    PlayStation: "PlayStation"
    Switch: "Switch"
    Xbox: "Xbox"
    Windows_Phone: "windows但是手机"
    Unknown: "未知的系统"
  # 玩家的ui样式
  UIProfile:
    classic: "classic ui"
    pocket: "pocket ui"
    Unknown: "Unknown ui"
  # 玩家的血量状态
  HP:
    low: "§e"
    medium: "§e"
    high: "§a"
  # 玩家的饱食度状态
  Food:
    low: "§e"
    medium: "§e"
    high: "§a