name: "Get pom.xml info"
description: "Get pom.xml info"

runs:
  using: "composite"
  steps:
    - name: 获取 pom.xml 的信息
      id: getPomInfo
      shell: bash
      run: |
        echo "groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: 输出获取到的 pom.xml 的信息
      shell: bash
      run: |
        echo Group id: ${{ steps.getPomInfo.outputs.groupId }}
        echo Artifact id: ${{ steps.getPomInfo.outputs.artifactd }}
        echo Version: ${{ steps.getPomInfo.outputs.version }}